name: SIEM Rule Sync
on:
  push:
    paths:
      - 'splunk/**'
      - 'qradar/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Sync Script
        env:
          SPLUNK_PASSWORD: ${{ secrets.SPLUNK_PASSWORD }}
        run: python scripts/sync_splunk.py
