name: SIEM Rule Sync
on:
  push:
    branches:
      - main  # Main-ə hər push olanda işləsin
  workflow_dispatch: # Bu sətir bizə "Run workflow" düyməsini verəcək (Manual işə salmaq üçün)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Sync Script
        env:
          SPLUNK_PASSWORD: ${{ secrets.SPLUNK_PASSWORD }}
        run: python scripts/sync_splunk.py
